site_name: 'GetRealT: Realty Web Portal'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/timitek/getrealt-quarx'

# Copyright
copyright: 'Copyright (c) 2017 timitek llc'

# Documentation and theme
docs_dir: 'docs'
theme: material

# Options
extra:
  logo: 'img/logo.png'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'timitek'
    twitter: 'timitek_llc'
  social:
    - type: 'github'
      link: 'https://github.com/timitek'
    - type: 'twitter'
      link: 'https://twitter.com/timitek_llc'
  disqus: 'disqus_timitek'

# Google Analytics
google_analytics:
  - 'UA-88740607-4'
  - 'auto'

extra_css: [ 'css/extra.css', 'css/ekko-lightbox.css' ]
extra_javascript: [ 'js/jquery.js', 'js/ekko-lightbox.js' ]

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'